Agnihotriketan/09122022
mouseinthehouse/Data-Structures-and-Algorithms-for-Beginners pull request #6
Opened 2022-12-09 09:05 UTC by agnihotriketan

2022-12-09 16:47 UTC, neetcode-gh commented on csharp/backtracking/TreeMaze.cs
> +namespace NeetCodeTester.backtracking
Should we remove the namespace to be consistent with the others?

2022-12-09 16:53 UTC, neetcode-gh requested changes
LGTM - just one comment, thanks.

2022-12-12 10:11 UTC, agnihotriketan commented
Ok will do

2022-12-12 11:53 UTC, agnihotriketan commented
done

2022-12-12 22:03 UTC, neetcode-gh commented
Thank you, looks good!

2022-12-12 22:03 UTC, merged